language: node_js
node_js:
  - "18"  # Use the Node.js version that matches your Docker image if specified

services:
  - docker

before_install:
  - docker-compose up -d  # Start services defined in docker-compose.yml
  - docker-compose ps  # Check if the containers are running

# install:
#   # Nothing needed here if dependencies are handled by Docker

# script:
#   - docker-compose exec app pnpm test  # Run tests inside the app container
