version: '3.8'

services:
  app:
    build: .
    command: ["pnpm", "run", "dev"]
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules  # Avoids overwriting `node_modules` in Docker

  mongo:
    image: mongo:5
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
