name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    env:
      MONGO_URI: mongodb://localhost:27017/testdb  # Configure MongoDB URI for testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t rest_api-app .
      
      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name app-container --env MONGO_URI=$MONGO_URI rest_api-app

      - name: Wait for application to be ready
        run: |
          until curl -s http://localhost:5000/health || [ "$SECONDS" -ge 30 ]; do sleep 2; done
      
      - name: Run tests inside Docker container
        run: |
          docker exec app-container pnpm test

      - name: Stop Docker container
        run: |
          docker stop app-container && docker rm app-container
